import { Router } from "express";
import { adminLogin, adminMe, requireAdmin } from "../controllers/adminController.js";
import { requireCaptcha } from "../middleware/captchaMiddleware.js";
import adminBroadcastRoutes from "./adminBroadcastRoutes.js";
import adminDiscountRoutes from "./adminDiscountRoutes.js";
import adminUserRoutes from "./adminUserRoutes.js";
import adminEventRoutes from "./adminEventRoutes.js";
import adminMembershipRoutes from "./adminMembershipRoutes.js";
import adminSponsorshipRoutes from "./adminSponsorshipRoutes.js";
import adminDonationRoutes from "./adminDonationRoutes.js";
import adminFinanceRoutes from "./adminFinanceRoutes.js";
import adminReportRoutes from "./adminReportRoutes.js";
import adminPageRoutes from "./adminPageRoutes.js";
import adminDashboardRoutes from "./adminDashboardRoutes.js";
import adminCustomerDashboardRoutes from "./adminCustomerDashboardRoutes.js";
import adminSettingsRoutes from "./adminSettingsRoutes.js";
import adminSessionRoutes from "./adminSessionRoutes.js";
import adminSessionBookingRoutes from "./adminSessionBookingRoutes.js";
import adminResourceRoutes from "./adminResourceRoutes.js";
import adminRsvpRoutes from "./adminRsvpRoutes.js";
import adminCheckoutFormRoutes from "./adminCheckoutFormRoutes.js";
import adminReviewRoutes from "./adminReviewRoutes.js";
import adminTeamMemberRoutes from "./adminTeamMemberRoutes.js";
import adminApiBuilderRoutes from "./adminApiBuilderRoutes.js";
import adminAccessRoutes from "./adminAccessRoutes.js";
import { syncTicketTailor } from "../controllers/adminMembershipController.js";

const router = Router();

router.post("/login", requireCaptcha(), adminLogin);
router.get("/me", requireAdmin, adminMe);
router.use("/dashboard", requireAdmin, adminDashboardRoutes);
router.use("/broadcasts", adminBroadcastRoutes);
router.use("/discounts", requireAdmin, adminDiscountRoutes);
router.use("/users", requireAdmin, adminUserRoutes);
router.use("/events", adminEventRoutes);
router.use("/sessions", adminSessionRoutes);
router.use("/session-bookings", adminSessionBookingRoutes);
router.use("/resources", adminResourceRoutes);
router.use("/rsvps", adminRsvpRoutes);
router.use("/checkout-forms", adminCheckoutFormRoutes);
router.use("/reviews", adminReviewRoutes);
router.use("/team-members", adminTeamMemberRoutes);
router.use("/api-builder", adminApiBuilderRoutes);
router.use("/access", adminAccessRoutes);
router.post("/tickettailor/sync", requireAdmin, syncTicketTailor);
router.use("/memberships", requireAdmin, adminMembershipRoutes);
router.use("/sponsorships", requireAdmin, adminSponsorshipRoutes);
router.use("/donations", requireAdmin, adminDonationRoutes);
router.use("/finance", requireAdmin, adminFinanceRoutes);
router.use("/reports", requireAdmin, adminReportRoutes);
router.use("/pages", requireAdmin, adminPageRoutes);
router.use("/customer-dashboard", requireAdmin, adminCustomerDashboardRoutes);
router.use("/settings", requireAdmin, adminSettingsRoutes);

export default router;
