import { Router } from "express";
import { getHealth } from "../controllers/healthController.js";
import paymentRoutes from "./paymentRoutes.js";
import paymentMethodRoutes from "./paymentMethodRoutes.js";
import authRoutes from "./authRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import newsletterRoutes from "./newsletterRoutes.js";
import publicRoutes from "./publicRoutes.js";
import contactRoutes from "./contactRoutes.js";
import testimonialRoutes from "./testimonialRoutes.js";
import membershipRoutes from "./membershipRoutes.js";
import adminRoutes from "./adminRoutes.js";
import discountRoutes from "./discountRoutes.js";
import checkoutRoutes from "./checkoutRoutes.js";
import bookingRoutes from "./bookingRoutes.js";
import eventRoutes from "./eventRoutes.js";
import ticketPublicRoutes from "./ticketPublicRoutes.js";
import verifyMembershipRoutes from "./verifyMembershipRoutes.js";
import webhookRoutes from "./webhookRoutes.js";

const router = Router();

router.get("/health", getHealth);
router.use("/verify-membership", verifyMembershipRoutes);
router.use("/public", publicRoutes);
router.use("/contact", contactRoutes);
router.use("/newsletter", newsletterRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/auth", authRoutes);
router.use("/payments", paymentRoutes);
router.use("/payment-methods", paymentMethodRoutes);
router.use("/membership", membershipRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/discounts", discountRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/booking", bookingRoutes);
router.use("/events", eventRoutes);
router.use("/tickets", ticketPublicRoutes);
router.use("/webhooks", webhookRoutes);
router.use("/admin", adminRoutes);

export default router;
