// Source data for ComponentRegistry / ComponentSchemaRegistry. Mirrors the field
// set CmsSectionEditor.jsx already renders for every section type (it's a
// uniform editor, not per-type forms) and the RENDERERS map in
// PageSectionRenderer.jsx. This is curated by hand, not generated by scanning
// source files at runtime — re-run the seed script manually after changes here.

export const COMPONENT_CATEGORIES = ["hero", "content", "media", "social-proof", "events", "cta", "structural"];

// Every section type exposes this same field set today (CmsSectionEditor.jsx
// shows it uniformly). The registry's value-add is naming/typing each field
// and giving every component type display metadata, not inventing new fields.
export const BASE_SECTION_FIELDS = [
  { key: "heading", label: "Heading", fieldType: "heading", category: "text", path: "content.heading" },
  { key: "subheading", label: "Subheading", fieldType: "subheading", category: "text", path: "content.subheading" },
  { key: "description", label: "Short description", fieldType: "paragraph", category: "text", path: "content.description" },
  { key: "longContent", label: "Long content", fieldType: "paragraph", category: "text", path: "content.longContent" },
  { key: "richText", label: "Rich text / HTML", fieldType: "richtext", category: "text", path: "content.richText" },
  { key: "bullets", label: "Bullet points", fieldType: "bullet_list", category: "text", path: "content.bullets" },
  { key: "heroImage", label: "Hero image", fieldType: "image", category: "media", path: "images.hero" },
  { key: "desktopImage", label: "Desktop image", fieldType: "image", category: "media", path: "images.desktop" },
  { key: "mobileImage", label: "Mobile image", fieldType: "mobile_image", category: "media", path: "images.mobile" },
  { key: "backgroundImage", label: "Background image", fieldType: "background_image", category: "media", path: "images.background" },
  { key: "iconImage", label: "Icon", fieldType: "icon", category: "media", path: "images.icon" },
  { key: "cardImage", label: "Card image", fieldType: "image", category: "media", path: "images.card" },
  { key: "ctas", label: "CTA buttons", fieldType: "cta_list", category: "cta", path: "ctas" },
  { key: "themeMode", label: "Theme mode", fieldType: "select", category: "style", path: "settings.themeMode" },
  { key: "textAlign", label: "Text alignment", fieldType: "select", category: "style", path: "settings.textAlign" },
  { key: "imagePosition", label: "Image position", fieldType: "select", category: "layout", path: "settings.imagePosition" },
  { key: "backgroundColor", label: "Background color", fieldType: "color", category: "style", path: "settings.backgroundColor" },
  { key: "overlayStrength", label: "Overlay strength", fieldType: "range", category: "style", path: "settings.overlayStrength" },
  { key: "isVisible", label: "Section visible", fieldType: "visibility", category: "layout", path: "isVisible" },
];

// componentKey -> display metadata. Keys match SECTION_TYPES in cmsConfig.js
// and RENDERERS in client/src/components/cms/PageSectionRenderer.jsx exactly.
export const COMPONENT_DEFINITIONS = [
  { componentKey: "hero", displayName: "Hero Section", category: "hero", icon: "IconPhoto", rendererKey: "hero", hasDedicatedRenderer: true },
  { componentKey: "breadcrumb_hero", displayName: "Breadcrumb Hero", category: "hero", icon: "IconRoute", rendererKey: "breadcrumb_hero", hasDedicatedRenderer: true },
  { componentKey: "text", displayName: "Text Section", category: "content", icon: "IconAlignLeft", rendererKey: "text", hasDedicatedRenderer: true },
  { componentKey: "image_text", displayName: "Image + Text", category: "content", icon: "IconColumns2", rendererKey: "image_text", hasDedicatedRenderer: true },
  { componentKey: "card_grid", displayName: "Card Grid", category: "content", icon: "IconLayoutGrid", rendererKey: "card_grid", hasDedicatedRenderer: true },
  { componentKey: "feature_cards", displayName: "Feature Cards", category: "content", icon: "IconStar", rendererKey: "feature_cards", hasDedicatedRenderer: true },
  { componentKey: "statistics", displayName: "Statistics", category: "content", icon: "IconChartBar", rendererKey: "statistics", hasDedicatedRenderer: true },
  { componentKey: "cta_banner", displayName: "CTA Banner", category: "cta", icon: "IconSpeakerphone", rendererKey: "cta_banner", hasDedicatedRenderer: true },
  { componentKey: "testimonials", displayName: "Testimonials", category: "social-proof", icon: "IconQuote", rendererKey: "testimonials", hasDedicatedRenderer: true },
  { componentKey: "event_slider", displayName: "Event Slider", category: "events", icon: "IconCalendarEvent", rendererKey: "event_slider", hasDedicatedRenderer: true },
  { componentKey: "featured_events", displayName: "Featured Events", category: "events", icon: "IconTicket", rendererKey: "featured_events", hasDedicatedRenderer: true },
  { componentKey: "gallery", displayName: "Gallery", category: "media", icon: "IconPhotoStar", rendererKey: "gallery", hasDedicatedRenderer: true },
  { componentKey: "video", displayName: "Video Section", category: "media", icon: "IconVideo", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "faq", displayName: "FAQ Section", category: "content", icon: "IconHelpCircle", rendererKey: "faq", hasDedicatedRenderer: true },
  { componentKey: "form", displayName: "Form Section", category: "structural", icon: "IconForms", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "sponsor_logos", displayName: "Sponsor Logos", category: "social-proof", icon: "IconBuildingBank", rendererKey: "sponsor_logos", hasDedicatedRenderer: true },
  { componentKey: "donation_cta", displayName: "Donation CTA", category: "cta", icon: "IconHeart", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "membership_pricing", displayName: "Membership Pricing", category: "content", icon: "IconCreditCard", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "contact_details", displayName: "Contact Details", category: "structural", icon: "IconAddressBook", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "footer_links", displayName: "Footer Links", category: "structural", icon: "IconLink", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "header_navigation", displayName: "Header Navigation", category: "structural", icon: "IconMenu2", rendererKey: "", hasDedicatedRenderer: false },
  { componentKey: "custom_html", displayName: "Custom HTML Block", category: "structural", icon: "IconCode", rendererKey: "custom_html", hasDedicatedRenderer: true },
  { componentKey: "team_members", displayName: "Our Team Slider", category: "social-proof", icon: "IconUsers", rendererKey: "team_members", hasDedicatedRenderer: true },
];
