/** Default automatic member discount rules — seeded via sync */

export const DEFAULT_MEMBER_DISCOUNTS = [
  {
    name: "Student Member Discount",
    type: "automatic_member",
    eligibleMembershipTypes: ["student"],
    discountType: "percentage",
    discountValue: 0,
    appliesTo: "tickets",
    allowStacking: true,
    status: "active",
  },
  {
    name: "Privileged Single Member Discount",
    type: "automatic_member",
    eligibleMembershipTypes: ["privilegedSingle"],
    discountType: "percentage",
    discountValue: 10,
    appliesTo: "tickets",
    allowStacking: true,
    status: "active",
  },
  {
    name: "Privileged Family Member Discount",
    type: "automatic_member",
    eligibleMembershipTypes: ["privilegedFamily"],
    discountType: "percentage",
    discountValue: 10,
    appliesTo: "tickets",
    allowStacking: true,
    status: "active",
  },
  {
    name: "Premium Single Member Discount",
    type: "automatic_member",
    eligibleMembershipTypes: ["premiumSingle"],
    discountType: "free_ticket",
    discountValue: 100,
    appliesTo: "tickets",
    allowStacking: false,
    status: "active",
  },
  {
    name: "Premium Family Member Discount",
    type: "automatic_member",
    eligibleMembershipTypes: ["premiumFamily"],
    discountType: "free_ticket",
    discountValue: 100,
    appliesTo: "tickets",
    allowStacking: false,
    status: "active",
  },
];
