/** Default team roster — display order matches About Us page spec. */
export const DEFAULT_TEAM_MEMBERS = [
  {
    displayOrder: 1,
    fullName: "Shivam Joshi",
    role: "President",
    designation: "President",
    teamCategory: "Executive Board",
    imageAssetKey: "team-1",
    isBoardMember: true,
    featured: true,
  },
  {
    displayOrder: 2,
    fullName: "Rucha Naik",
    role: "Executive Board Member",
    designation: "Board Member",
    teamCategory: "Executive Board",
    imageAssetKey: "team-4",
    isBoardMember: true,
  },
  {
    displayOrder: 3,
    fullName: "Saurabh Sharma",
    role: "Secretary General",
    designation: "Secretary General",
    teamCategory: "Executive Board",
    imageAssetKey: "team-3",
    isBoardMember: true,
  },
  {
    displayOrder: 4,
    fullName: "Rajendra Rade",
    role: "Treasurer",
    designation: "Treasurer",
    teamCategory: "Executive Board",
    imageAssetKey: "team-2",
    isBoardMember: true,
  },
  {
    displayOrder: 5,
    fullName: "Kirtee Kulkarni",
    role: "Social Media Manager",
    designation: "Social Media",
    teamCategory: "Communications",
    imageAssetKey: "team-5",
  },
  {
    displayOrder: 6,
    fullName: "Sreedevi Mahadevan",
    role: "Event Manager",
    designation: "Event Manager",
    teamCategory: "Events",
    imageAssetKey: "team-6",
  },
  {
    displayOrder: 7,
    fullName: "Priyanka Bhide",
    role: "Executive Board Member",
    designation: "Board Member",
    teamCategory: "Executive Board",
    imageAssetKey: "team-8",
    isBoardMember: true,
  },
  {
    displayOrder: 8,
    fullName: "Deepti Madaram",
    role: "PR Manager Den Haag",
    designation: "PR Manager",
    teamCategory: "PR & Communications",
    imageAssetKey: "team-14",
  },
  {
    displayOrder: 9,
    fullName: "Yazhini Sivakumar",
    role: "Event Management Team",
    designation: "Events Team",
    teamCategory: "Events",
    imageAssetKey: "team-9",
  },
  {
    displayOrder: 10,
    fullName: "Anshika Singh Bais",
    role: "PR Manager",
    designation: "PR Manager",
    teamCategory: "PR & Communications",
    imageAssetKey: "team-12",
  },
  {
    displayOrder: 11,
    fullName: "Shivani Trifaley",
    role: "PR Manager",
    designation: "PR Manager",
    teamCategory: "PR & Communications",
    imageAssetKey: "team-11",
  },
  {
    displayOrder: 12,
    fullName: "Aditya Wankhade",
    role: "Event Management Team",
    designation: "Events Team",
    teamCategory: "Events",
    imageAssetKey: "team-7",
  },
  {
    displayOrder: 13,
    fullName: "Parth Upadhyay",
    role: "Event Management Team",
    designation: "Events Team",
    teamCategory: "Events",
    imageAssetKey: "team-13",
  },
  {
    displayOrder: 14,
    fullName: "Dr. Manasi Moharil",
    role: "Event Management Team",
    designation: "Events Team",
    teamCategory: "Events",
    imageAssetKey: "team-10",
  },
];
