export const BUSINESS_CATEGORIES = [
  "fashion",
  "beauty",
  "food",
  "tech",
  "art",
  "wellness",
  "education",
  "home",
  "events",
  "consulting",
  "media",
  "other",
  // Global marketplace additions
  "grocery",
  "cosmetics",
  "travel",
  "food_wholesale",
  "beverages",
  "health",
  "household",
  "electronics",
];

export const BUSINESS_CATEGORY_LABELS = {
  fashion: "Fashion & Clothing",
  beauty: "Beauty & Wellness",
  food: "Food & Drink",
  tech: "Tech & Digital",
  art: "Art & Creative",
  wellness: "Health & Wellness",
  education: "Education & Coaching",
  home: "Home & Living",
  events: "Events & Entertainment",
  consulting: "Consulting & Services",
  media: "Media & Content",
  other: "Other",
  grocery: "Grocery & Supermarket",
  cosmetics: "Cosmetics & Personal Care",
  travel: "Travel & Tourism",
  food_wholesale: "Food Wholesale & Distribution",
  beverages: "Beverages & Drinks",
  health: "Health & Pharmaceuticals",
  household: "Household & Cleaning",
  electronics: "Electronics & Appliances",
};

export const CATEGORY_ICONS = {
  fashion: "👗",
  beauty: "💅",
  food: "🍽️",
  tech: "💻",
  art: "🎨",
  wellness: "🌿",
  education: "📚",
  home: "🏡",
  events: "🎉",
  consulting: "💼",
  media: "📱",
  other: "✨",
  grocery: "🛒",
  cosmetics: "💄",
  travel: "✈️",
  food_wholesale: "📦",
  beverages: "🥤",
  health: "💊",
  household: "🏠",
  electronics: "🔌",
};
