import ExcelJS from "exceljs";
import { formatMoney } from "../utils/financeUtils.js";

function addSheet(workbook, name, headers, rows) {
  const sheet = workbook.addWorksheet(name);
  sheet.addRow(headers);
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0891B2" } };
  for (const row of rows) {
    sheet.addRow(row);
  }
  sheet.columns.forEach((col) => {
    col.width = 18;
  });
}

export async function buildBudgetExcel(budget, formatted) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Stichting The V.O.I.C.E. NL";

  addSheet(workbook, "Summary", ["Field", "Value"], [
    ["Event", budget.eventName],
    ["Event Date", formatted.eventDate],
    ["Venue", budget.venue || ""],
    ["Status", budget.status],
    ["Planned Income", formatted.plannedIncomeTotal],
    ["Actual Income", formatted.actualIncomeTotal],
    ["Planned Expenses", formatted.plannedExpenseTotal],
    ["Actual Expenses", formatted.actualExpenseTotal],
    ["Planned Net", formatted.plannedNetResult],
    ["Actual Net", formatted.actualNetResult],
    ["Variance", formatted.variance],
  ]);

  addSheet(
    workbook,
    "Income",
    ["Category", "Description", "Planned", "Actual", "Status", "Source", "Notes"],
    (budget.plannedIncomeLines || []).map((l, i) => {
      const actual = budget.actualIncomeLines?.[i];
      return [
        l.category,
        l.description,
        formatMoney(l.plannedAmount),
        formatMoney(actual?.actualAmount || l.actualAmount || 0),
        actual?.paymentStatus || l.paymentStatus,
        l.sourceModule,
        l.notes,
      ];
    })
  );

  addSheet(
    workbook,
    "Expenses",
    ["Category", "Vendor", "Description", "Planned", "Actual", "VAT%", "Status", "Notes"],
    (budget.plannedExpenseLines || []).map((l, i) => {
      const actual = budget.actualExpenseLines?.[i];
      return [
        l.category,
        l.vendorPayee || actual?.vendorPayee,
        l.description,
        formatMoney(l.plannedAmount),
        formatMoney(actual?.actualAmount || l.actualAmount || 0),
        l.vatRate,
        actual?.paymentStatus || l.paymentStatus,
        l.notes,
      ];
    })
  );

  addSheet(workbook, "Variance", ["Metric", "Value"], [
    ["Income Variance", formatted.incomeVariance],
    ["Expense Variance", formatted.expenseVariance],
    ["Total Variance", formatted.variance],
    ["Break-even Attendance", budget.breakEvenAttendance || ""],
    ["Avg Revenue/Attendee", formatted.avgRevenuePerAttendee],
    ["Avg Cost/Attendee", formatted.avgCostPerAttendee],
  ]);

  addSheet(workbook, "Notes", ["Notes"], [[budget.notes || ""]]);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function buildAuditReportExcel(report, summary) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Stichting The V.O.I.C.E. NL";

  addSheet(workbook, "Cover", ["Field", "Value"], [
    ["Title", report.title],
    ["Type", report.reportType],
    ["Period Start", report.dateRangeStart],
    ["Period End", report.dateRangeEnd],
    ["Generated By", report.generatedByName],
    ["Generated At", report.generatedAt],
  ]);

  if (summary) {
    addSheet(workbook, "Executive Summary", ["Metric", "Value"], Object.entries(summary.executive || {}));
    addSheet(workbook, "Income", ["Source", "Amount"], Object.entries(summary.income || {}));
    addSheet(workbook, "Expenses", ["Category", "Amount"], Object.entries(summary.expenses || {}));
    addSheet(workbook, "Events", ["Event", "Net Result"], (summary.events || []).map((e) => [e.name, e.netResult]));
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function buildInvoicesExcel(invoices) {
  const workbook = new ExcelJS.Workbook();
  addSheet(
    workbook,
    "Invoices",
    [
      "Invoice Number",
      "Client",
      "Email",
      "Related Type",
      "Event",
      "Invoice Date",
      "Due Date",
      "Total",
      "Paid",
      "Balance",
      "Payment Status",
      "Sent Status",
    ],
    invoices.map((inv) => [
      inv.invoiceNumber,
      inv.clientName || inv.companyName,
      inv.email,
      inv.relatedType,
      inv.relatedEventName,
      inv.invoiceDate,
      inv.dueDate,
      inv.totalAmountFormatted,
      inv.amountPaidFormatted,
      inv.balanceDueFormatted,
      inv.paymentStatus,
      inv.sentStatus,
    ])
  );
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
