import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import ReportExportLog from "../models/ReportExportLog.js";
import { nextReportPublicId } from "./reportAnalyticsService.js";
import { collectPdfBuffer } from "../utils/pdfBuffer.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HEADER_LOGO_PATH = path.join(__dirname, "..", "..", "..", "client", "src", "assets", "header-logo.png");
const FOOTER_TEXT = "© 2026 Stichting The V.O.I.C.E. NL. All rights reserved.";

function logoPath() {
  return fs.existsSync(HEADER_LOGO_PATH) ? HEADER_LOGO_PATH : null;
}

function pdfBuffer(buildFn) {
  const doc = new PDFDocument({ size: "A4", margins: { top: 40, bottom: 50, left: 48, right: 48 }, bufferPages: true });
  return collectPdfBuffer(doc, buildFn);
}

function drawPdfHeader(doc, title, subtitle, generatedBy) {
  const left = doc.page.margins.left;
  const logo = logoPath();
  let y = 36;
  if (logo) {
    doc.image(logo, left, y, { height: 40 });
    y += 48;
  }
  doc.fillColor("#002147").font("Helvetica-Bold").fontSize(16).text(title, left, y);
  if (subtitle) doc.fillColor("#666").font("Helvetica").fontSize(10).text(subtitle, left, doc.y + 4);
  if (generatedBy) doc.text(`Generated by: ${generatedBy}`, left, doc.y + 4);
  doc.text(`Generated: ${new Date().toLocaleString("nl-NL")}`, left, doc.y + 2);
  doc.moveDown(1.5);
}

function drawPdfFooter(doc) {
  const y = doc.page.height - 36;
  doc.fillColor("#084d69").font("Helvetica").fontSize(8).text(FOOTER_TEXT, 0, y, { width: doc.page.width, align: "center" });
}

export async function exportReportPdf({ title, subtitle, summary = [], tables = [], generatedBy, adminId }) {
  const buffer = await pdfBuffer((doc) => {
    drawPdfHeader(doc, title, subtitle, generatedBy);
    if (summary.length) {
      doc.fillColor("#000").font("Helvetica-Bold").fontSize(11).text("Summary");
      doc.moveDown(0.3);
      summary.forEach((s) => {
        doc.font("Helvetica").fontSize(9).text(`${s.label}: ${s.value}`);
      });
      doc.moveDown(1);
    }
    tables.forEach((table) => {
      if (table.title) {
        doc.font("Helvetica-Bold").fontSize(10).text(table.title);
        doc.moveDown(0.3);
      }
      const cols = table.columns || [];
      const widths = cols.map(() => (doc.page.width - 96) / Math.max(cols.length, 1));
      let y = doc.y;
      doc.font("Helvetica-Bold").fontSize(8);
      let x = doc.page.margins.left;
      cols.forEach((col, i) => {
        doc.text(String(col), x, y, { width: widths[i], lineBreak: false });
        x += widths[i];
      });
      y += 14;
      doc.font("Helvetica").fontSize(8);
      (table.rows || []).slice(0, 80).forEach((row) => {
        if (y > doc.page.height - 60) {
          doc.addPage();
          y = doc.page.margins.top;
        }
        x = doc.page.margins.left;
        cols.forEach((col, i) => {
          doc.text(String(row[col] ?? ""), x, y, { width: widths[i], lineBreak: false });
          x += widths[i];
        });
        y += 12;
      });
      doc.y = y + 8;
      doc.moveDown(0.5);
    });
    drawPdfFooter(doc);
  });

  const exportId = await nextReportPublicId("RPT");
  await ReportExportLog.create({
    exportId,
    reportType: title,
    format: "pdf",
    generatedBy: adminId,
    status: "completed",
  });

  return { buffer, exportId, filename: `${title.replace(/\s+/g, "-").toLowerCase()}.pdf` };
}

export async function exportReportExcel({ title, summary = [], sheets = [], generatedBy, adminId }) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = generatedBy || "V.O.I.C.E. NL Admin";
  workbook.created = new Date();

  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.addRow([title]);
  summarySheet.addRow([`Generated: ${new Date().toLocaleString("nl-NL")}`]);
  summarySheet.addRow([]);
  summary.forEach((s) => summarySheet.addRow([s.label, s.value]));

  sheets.forEach((sheet) => {
    const ws = workbook.addWorksheet((sheet.name || "Data").slice(0, 31));
    const cols = sheet.columns || [];
    if (cols.length) ws.addRow(cols);
    (sheet.rows || []).forEach((row) => {
      if (Array.isArray(row)) ws.addRow(row);
      else ws.addRow(cols.map((c) => row[c]));
    });
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const exportId = await nextReportPublicId("RPT");
  await ReportExportLog.create({
    exportId,
    reportType: title,
    format: "excel",
    generatedBy: adminId,
    status: "completed",
  });

  return { buffer, exportId, filename: `${title.replace(/\s+/g, "-").toLowerCase()}.xlsx` };
}

export function exportReportCsv({ columns, rows }) {
  const escape = (v) => {
    const s = String(v ?? "");
    return s.includes(",") || s.includes('"') || s.includes("\n") ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [columns.map(escape).join(",")];
  rows.forEach((row) => {
    if (Array.isArray(row)) lines.push(row.map(escape).join(","));
    else lines.push(columns.map((c) => escape(row[c])).join(","));
  });
  return Buffer.from(lines.join("\n"), "utf-8");
}
